apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
  namespace: project01
spec:
  params:
    - default: 'https://github.com/mmartofel/kuberneter-probes'
      name: git-repo
      type: string
    - default: main
      name: git-branch
      type: string
  tasks:
    - name: git-clone-1-8-0
      params:
        - name: url
          value: $(params.git-repo)
        - name: revision
          value: $(params.git-branch)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'false'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:cadf614a6044ee37397de3abe7674827ecab225e7fac9fb123eff5473e2c4003
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone-1-8-0
      workspaces:
        - name: output
          workspace: code-workspace
  workspaces:
    - name: code-workspace
