apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crud-application
spec:
  destination:
    name: ''
    namespace: probes
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/crud-application
    repoURL: 'https://github.com/mmartofel/kuberneter-probes'
    targetRevision: HEAD
  project: no-kubernetes-probes