apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crud-application
spec:
  destination:
    name: 'CRUD microservice with database and frontend'
    namespace: crud-application
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment
    repoURL: 'https://github.com/mmartofel/kuberneter-probes'
    targetRevision: HEAD
  project: no-kubernetes-probes